// <auto-generated />
namespace BloggerPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class otp_added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(otp_added1));
        
        string IMigrationMetadata.Id
        {
            get { return "202204150029455_otp_added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
